Updated to work with a more recent version of rustls
veracruz-project/nitro-enclave-attestation-document pull request #5
Opened 2022-04-22 19:16 UTC by mathias-arm

This branch also merge into main the changes done in `veracruz-v2` (un-pin `serde_with`.

2022-04-28 15:18 UTC, dreemkiller requested changes

2022-04-28 15:18 UTC, dreemkiller commented on src/lib.rs
> +        //certs.push(cert);
commented out code

2022-04-29 12:36 UTC, Mikescops commented on src/lib.rs
> +        let _verified = verifier.verify_client_cert(&rustls::Certificate(document.certificate.clone()), &certs[..], std::time::SystemTime::now()).map_err(|err| {
```suggestion
        let _verified = verifier.verify_client_cert(&rustls::Certificate(document.certificate.clone()), &certs, std::time::SystemTime::now()).map_err(|err| {
```

Is `[..]` really needed here?

2022-04-29 12:38 UTC, Mikescops approved these changes, later dismissed
Hello,
Thanks for opening the PR, I did the same changes on my side without noticing your PR, I can confirm it works well :)

2022-04-29 13:49 UTC, dreemkiller submitted a review, later dismissed

2022-05-02 14:34 UTC, dreemkiller submitted a review, later dismissed

2022-05-02 15:01 UTC, dreemkiller approved these changes

2022-05-02 15:02 UTC, merged